### ISSUE TITLE
Add context to Ito standard configuration

### ISSUE THREAD

**Issue by mhayescs19** [mhayescs19/nu-ve-hume-starter#10]
## Objective
- Determine how to inject personalization from Ito default configuration for additional user specific context.

## Tasks
- [x] Investigate documentation -> use session settings to inject context via `<VoiceProvider>`
- [x] Extract user metadata from Clerk with useUser() React hook
- [x] Trim context injection from user messages

## Resources
- [Hume Chat Websocket Session Settings](https://dev.hume.ai/reference/empathic-voice-interface-evi/chat/chat#send.Session%20Settings.type): use session settings format only, no need to create a web socket connection
