### ISSUE TITLE
Integrate with Clerk (Authentication Service)

### ISSUE THREAD

**Issue by mhayescs19** [mhayescs19/nu-ve-hume-starter#5]
## Objective
 - Allow users to create accounts with sign up form (or users will be created from an admin, users will log in with username and password)
- Log in with user name and password
- Hamburger menu item for profile and prep for settings

## Tasks
- [x] Create Clerk App
- [x] Wrap Next.js project with `<ClerkProvider \>`
- [x] Add Login component
- [x] Add Logout component
- [x] Add shadcn drop down menu

## Reach
Admin adds a custom prompt into the account and Hume would access the prompt stored in the account and load a custom configuration.

## Extra Details
- [Clerk Get Started Doc](https://dashboard.clerk.com/apps/app_2moUAQPGVuUd76WqazJk3WuhrGT/instances/ins_2moUAXP9IGgGqW7ejEBMejbeGun)
- [Sign out Compoen](https://clerk.com/docs/components/unstyled/sign-out-button)
